name: Unit tests

on:
  push:
    branches: [master, main, next]
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build

      - name: Run tests
        run: npm run test:unit
